### ISSUE TITLE
data params of the call "create annotations" ?

### ISSUE THREAD

**Issue by mandiayba** [openminted/omtd-aero#1]
I don't understand what are the data params of the call ["create annotations"](https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_annotations) i.e. why 'None' into 'data params' of that call ?  

FYI: I'm implementing aero in alvisae

@reckart

**Comment by reckart** [comment]
That looks like a copy-paste bug. There should be data parameters. Let me check...

**Comment by reckart** [comment]
@mandiayba thanks for noticing this! I have added the missing information and updated the rendered version here: https://openminted.github.io/releases/aero-spec/1.0.0/omtd-aero/#_create_annotations

**Comment by reckart** [comment]
Btw. in case it might help you in any way - here is a link to the WebAnno implementation: https://github.com/webanno/webanno/blob/master/webanno-remote/src/main/java/de/tudarmstadt/ukp/clarin/webanno/webapp/remoteapi/RemoteApiController2.java

**Comment by mandiayba** [comment]
That will help yes, thanks.

**Comment by reckart** [comment]
If you notice any differences between the protocol specs and the WebAnno implementation, please let me know.
